image:
  repository: ghcr.io/miguelndecarvalho/speedtest-exporter
  tag: v3.5.4@sha256:f1064d49124c7fc45faabb87c6c876a2fd04e92b3dc14d4b871301217ba30fed
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        protocol: tcp
        port: 9798
metrics:
  main:
    enabled: true
    type: "servicemonitor"
    endpoints:
      - port: main
        path: /metrics
        interval: 1h
    prometheusRule:
      enabled: true
portal:
  open:
    enabled: true
securityContext:
  container:
    PUID: 568
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
