image:
  repository: ghcr.io/ac1dburnz/rtorrent-rutorrent-cross-seed
  pullPolicy: IfNotPresent
  tag: 4.2.9-0.9.8_2-0.13.8_1@sha256:1493a63f55c08658982e892e30af5c149001f091eeea0b23d59b0986ce6983a0
  
securityContext:
  container:
    PUID: 33
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        protocol: http
        port: 8080
  rtorrent:
    enabled: true
    ports:
      rtorrent:
        enabled: true
        protocol: tcp
        port: 33942
  xmlrpc:
    enabled: true
    ports:
      xmlrpc:
        enabled: true
        protocol: http
        port: 8000
  dht:
    enabled: true
    ports:
      dht:
        enabled: true
        protocol: udp
        port: 6881
  webdav:
    enabled: true
    ports:
      webdav:
        enabled: true
        protocol: http
        port: 9000
  rtinc:
    enabled: true
    ports:
      rtinc:
        enabled: true
        port: 50000

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            RUTORRENT_PORT: "{{ .Values.service.main.ports.main.port }}"
            PORT_RTORRENT: "{{ .Values.service.rtorrent.ports.rtorrent.port }}"
            RT_DHT_PORT: "{{ .Values.service.dht.ports.dht.port }}"
            XMLRPC_PORT: "{{ .Values.service.xmlrpc.ports.xmlrpc.port }}"
            WEBDAV_PORT: "{{ .Values.service.webdav.ports.webdav.port }}"
            RT_INC_PORT: "{{ .Values.service.rtinc.ports.rtinc.port }}"

persistence:
  data:
    enabled: true
    mountPath: "/data"
  downloads:
    enabled: true
    mountPath: "/downloads"
  passwd:
    enabled: true
    mountPath: "/passwd"

portal:
  open:
    enabled: true
