image:
  repository: http://ghcr.io/ac1dburnz/rtorrent-rutorrent-cross-seed
  pullPolicy: IfNotPresent
  tag: 4.2.10-0.9.8-0.13.8@sha256:c320253313da2c5e263894b499ef0ca39a5b5d2aaf8c0fba49f5711f20c70efa 
securityContext:
  container:
    PUID: 33
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        protocol: http
        port: 8080
  rtorrent:
    enabled: true
    ports:
      rtorrent:
        enabled: true
        protocol: tcp
        port: 33942
  xmlrpc:
    enabled: true
    ports:
      xmlrpc:
        enabled: true
        protocol: http
        port: 8000
  dht:
    enabled: true
    ports:
      dht:
        enabled: true
        protocol: udp
        port: 6881
  webdav:
    enabled: true
    ports:
      webdav:
        enabled: true
        protocol: http
        port: 9000
  rtinc:
    enabled: true
    ports:
      rtinc:
        enabled: true
        port: 50000

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          env:
            RUTORRENT_PORT: "{{ .Values.service.main.ports.main.port }}"
            PORT_RTORRENT: "{{ .Values.service.rtorrent.ports.rtorrent.port }}"
            RT_DHT_PORT: "{{ .Values.service.dht.ports.dht.port }}"
            XMLRPC_PORT: "{{ .Values.service.xmlrpc.ports.xmlrpc.port }}"
            WEBDAV_PORT: "{{ .Values.service.webdav.ports.webdav.port }}"
            RT_INC_PORT: "{{ .Values.service.rtinc.ports.rtinc.port }}"

persistence:
  data:
    enabled: true
    mountPath: "/data"
  downloads:
    enabled: true
    mountPath: "/downloads"
  passwd:
    enabled: true
    mountPath: "/passwd"

portal:
  open:
    enabled: true
