image:
  repository: ghcr.io/ac1dburnz/rtorrent-rutorrent-cross-seed
  pullPolicy: IfNotPresent
  tag: 4.3.0-0.9.8-0.13.8@sha256:79297de0463d080f75f535d3c33c61d429396c26d3e3949c916e4b9cdb2dbddb
  
exportarrImage:
  repository: ghcr.io/thde/rtorrent_exporter
  pullPolicy: IfNotPresent
  tag: v1.3.1@sha256:0a7716d8b434f8ecf9370053c46e099cfde3c98a60555d3128e07e6da7438fcd

securityContext:
  container:
    PUID: 33
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        protocol: http
        port: 8080
  rtorrent:
    enabled: true
    ports:
      rtorrent:
        enabled: true
        protocol: tcp
        port: 2468
  xmlrpc:
    enabled: true
    ports:
      xmlrpc:
        enabled: true
        protocol: http
        port: 8000
  dht:
    enabled: true
    ports:
      dht:
        enabled: true
        protocol: udp
        port: 6881
  webdav:
    enabled: true
    ports:
      webdav:
        enabled: true
        protocol: http
        port: 9000
  rtinc:
    enabled: true
    ports:
      rtinc:
        enabled: true
        port: 50000
  xseed:
    enabled: true
    ports:
      csmovie:
        enabled: true
        port: 2469
  metrics:
    enabled: true
    type: ClusterIP
    targetSelector: exportarr
    ports:
      metrics:
        enabled: true
        port: 9135
        targetSelector: exportarr

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            readiness:
              enabled: false
            liveness:
              enabled: false
            startup:
              enabled: false
          env:
            RUTORRENT_PORT: "{{ .Values.service.main.ports.main.port }}"
            PORT_RTORRENT: "{{ .Values.service.rtorrent.ports.rtorrent.port }}"
            RT_DHT_PORT: "{{ .Values.service.dht.ports.dht.port }}"
            XMLRPC_PORT: "{{ .Values.service.xmlrpc.ports.xmlrpc.port }}"
            WEBDAV_PORT: "{{ .Values.service.webdav.ports.webdav.port }}"
            RT_INC_PORT: "{{ .Values.service.rtinc.ports.rtinc.port }}"
            RU_REMOVE_CORE_PLUGINS: false

  exportarr:
    enabled: true
    type: Deployment
    strategy: RollingUpdate
    replicas: 1
    podSpec:
      containers:
        exportarr:
          primary: true
          enabled: true
          imageSelector: exportarrImage
          args:
            - --rtorrent.scrape-uri={{ printf "http://%s-xmlrpc.%s.svc.cluster.local:%v/RPC2/" .Release.Name .Release.Namespace .Values.service.xmlrpc.ports.xmlrpc.port }}
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          env:
            INTERFACE: 0.0.0.0
            PORT: "{{ .Values.service.metrics.ports.metrics.port }}"
            URL: '{{ printf "http://%s-xmlrpc.%s.svc.cluster.local:%v/RPC2/" .Release.Name .Release.Namespace .Values.service.xmlrpc.ports.xmlrpc.port }}'
            ENABLE_ADDITIONAL_METRICS: false
            ENABLE_UNKNOWN_QUEUE_ITEMS: false

persistence:
  data:
    enabled: true
    mountPath: "/data"
  downloads:
    enabled: true
    mountPath: "/downloads"
  passwd:
    enabled: true
    mountPath: "/passwd"
          
metrics:
    main:
      enabled: true
      type: "servicemonitor"
      endpoints:
        - port: metrics
          path: /metrics
      targetSelector: metrics
      prometheusRule:
        enabled: false

portal:
  open:
    enabled: true
            
