image:
  repository: ghcr.io/ac1dburnz/rtorrent-rutorrent-cross-seed
  pullPolicy: IfNotPresent
  tag: 4.2.7-0.9.8-0.13.8@sha256:9c3f973874299dd9a9227e4fb47119b8634e6dda777fdc9f8467e7e398db9be3

securityContext:
  container:
    PUID: 33
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        protocol: http
        port: 8080
  rtorrent:
    enabled: true
    ports:
      rtorrent:
        enabled: true
        protocol: tcp
        port: 2468
  xmlrpc:
    enabled: true
    ports:
      xmlrpc:
        enabled: true
        protocol: http
        port: 8000
  dht:
    enabled: true
    ports:
      dht:
        enabled: true
        protocol: udp
        port: 6881
  webdav:
    enabled: true
    ports:
      webdav:
        enabled: true
        protocol: http
        port: 9000
  rtinc:
    enabled: true
    ports:
      rtinc:
        enabled: true
        port: 50000

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            RUTORRENT_PORT: "{{ .Values.service.main.ports.main.port }}"
            PORT_RTORRENT: "{{ .Values.service.rtorrent.ports.rtorrent.port }}"
            RT_DHT_PORT: "{{ .Values.service.dht.ports.dht.port }}"
            XMLRPC_PORT: "{{ .Values.service.xmlrpc.ports.xmlrpc.port }}"
            WEBDAV_PORT: "{{ .Values.service.webdav.ports.webdav.port }}"
            RT_INC_PORT: "{{ .Values.service.rtinc.ports.rtinc.port }}"

persistence:
  data:
    enabled: true
    mountPath: "/data"
  downloads:
    enabled: true
    mountPath: "/downloads"
  passwd:
    enabled: true
    mountPath: "/passwd"

portal:
  open:
    enabled: true
