image:
  repository: ac1dburn/dashy
  tag: 2.1.1@sha256:c6e085039ad5d28c5e02f1ab7faa78614f53dfa49c514e92e6de1d486fcf1ab6
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 10310
        protocol: http
        targetPort: 80

dashy:
  # Enable config file mount from host path
  enabled: false
  configFileHostPath: ""
  configFileHostReadOnly: true

# Leave empty if you plan to use config file from host path
dashyConfig:
  {}
  # pageInfo:
  #   title: Home Lab

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            NODE_ENV: production
          probes:
            liveness:
              enabled: true
              custom: true
              spec:
                exec:
                  command:
                    - node
                    - /app/services/healthcheck
            readiness:
              enabled: true
              custom: true
              spec:
                exec:
                  command:
                    - node
                    - /app/services/healthcheck
            startup:
              enabled: true
              custom: true
              spec:
                exec:
                  command:
                    - node
                    - /app/services/healthcheck

persistence:
  icons:
    enabled: true
    mountPath: /app/public/item-icons

portal:
  open:
    enabled: true
